spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://49.232.146.162:3306/blog_system?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: countSql
